### ISSUE TITLE
HANDS-ON LAB : Using Firestore with Cloud IoT Core for Device Configuration

### ISSUE THREAD

**Issue by waterstar** [bigdatasg/iotoncloud#1]
Got following error when deploying the firebase function : 

<img width="1438" alt="Screenshot 2019-08-18 at 12 03 42 PM" src="https://user-images.githubusercontent.com/8625997/63220773-ee746d80-c1c0-11e9-82b7-c04a95d8c9b2.png">

Tried to create a service account on IAM with the login email and tried again but same result :(

**Comment by DivyaGe** [comment]
Qwiklabs team is looking into the issue . Will update once it's gets resolved. 
![QwiklabsError](https://user-images.githubusercontent.com/16093639/63490967-8e473980-c4e8-11e9-97f5-a28c8338644e.PNG)

**Comment by DivyaGe** [comment]
Qwiklab team resolved the issue.
<img width="1440" alt="Screenshot 2019-08-24 at 9 59 23 AM" src="https://user-images.githubusercontent.com/16093639/63631141-f23b4080-c655-11e9-845f-e1fe5cbb532c.png">

**Comment by waterstar** [comment]
confirmed the issue is solved. Thanks.

<img width="1439" alt="Screenshot 2019-08-25 at 10 11 42 PM" src="https://user-images.githubusercontent.com/8625997/63651564-9e7d4400-c788-11e9-9ed4-4ea4ed95fc03.png">
#
